from typing import TypedDict, Optional, List, Dict, Any
from app.ai.schemas.extracted_data import ComplaintExtractedData

class DocumentState(TypedDict):
    """
    Represents the state of the document as it moves through the LangGraph pipeline.
    Each node in the graph will read and optionally update fields in this dictionary.
    """
    document_id: str                   # Unique tracker for this job
    raw_text: str                      # Raw parsed text from PDF/Email/Image
    cleaned_text: Optional[str]        # Preprocessed, OCR-cleaned text
    
    # Extraction Outputs
    extracted_data: Optional[ComplaintExtractedData] 
    
    # Intelligence Enrichments
    summary: Optional[str]             # Executive summary generated by LLM
    patient_risk: Optional[str]        # High/Medium/Low
    business_risk: Optional[str]       # High/Medium/Low
    regulatory_risk: Optional[str]     # High/Medium/Low
    overall_risk: Optional[str]        # Aggregated risk level
    
    root_cause_suggestion: Optional[str] 
    capa_suggestion: Optional[str]     # Corrective and Preventive Actions
    
    # Validation & Metadata
    validation_errors: List[str]       # Errors caught by Pydantic or custom validators
    missing_fields: List[str]          # Fields that LLM noted were missing
    processing_time_ms: int            # Track execution speed
    status: str                        # e.g., "processing", "completed", "failed"
    error_message: Optional[str]       # Fatal error message if pipeline fails
